---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-app
  namespace: argocd
spec:
  project: default
  source:
    # IMPORTANT: Replace this URL with your own GitHub repository!
    # The repository should contain the deployment.yaml file from confs/app/
    # Example: https://github.com/YOUR_USERNAME/iot-argocd-config
    repoURL: https://github.com/eddard-contessa/econtess-IoT.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
