login: urosby
box: generic/ubuntu2204
provider: libvirt

resources:
  cpus: 1
  memory: 1024

synced_folder:
  type: 9p
  # "mapped" is the usual working mode for writable 9p shares in vagrant-libvirt
  accessmode: mapped
  msize: 262144

vms:
  - name: S
    hostname: S
    ip: 192.168.56.110
    script: scripts/server.sh
  - name: SW
    hostname: SW
    ip: 192.168.56.111
    script: scripts/worker.sh
