LOGIN = "urosby"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  #########################
  # K3s Server VM
  #########################
  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"

    # Private network
    server.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__network_address: "192.168.56.0"

    # VM resources
    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    # Provision K3s server
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  #########################
  # K3s Worker VM
  #########################
  config.vm.define "#{LOGIN}SW" do |worker|
    worker.vm.hostname = "#{LOGIN}SW"

    # Private network
    worker.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__network_address: "192.168.56.0"

    # VM resources
    worker.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    # Provision K3s agent
    # Worker script already waits for /vagrant/confs/node-token
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
